/**
 * The generated bindings boundary.
 *
 * The file under `src/generated` is machine output from `tauri-specta`. Two
 * things must hold at this boundary. It is genuinely generated, so a hand edit
 * is visible. And a typed domain failure is a different result from a transport
 * rejection, so a caller can tell "the backend refused" from "the call never
 * arrived" (spec 7.8.2, spec 8.2, spec 8.4).
 *
 * Byte-for-byte equality with the exporter is proved by the Rust test
 * `src-tauri/tests/bindings.rs`, which regenerates the file and compares.
 */
import { readFileSync } from "node:fs";

import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@tauri-apps/api/core", () => ({
  invoke: () => Promise.reject(new Error("transport is down")),
}));
vi.mock("@tauri-apps/api/event", () => ({
  listen: () => Promise.resolve(() => undefined),
}));

import { commands, events } from "../src/generated/bindings";
import { reportAsync } from "../src/shared/ipc/report";
import { getRendererState, resetRendererState } from "../src/shared/state/store";

// Vitest runs from the repository root, where the generated file sits.
const GENERATED_SOURCE = readFileSync("src/generated/bindings.ts", "utf8");

beforeEach(() => {
  resetRendererState();
});

describe("the generated bindings file", () => {
  it("carries the generator header, so a hand edit is visible", () => {
    expect(GENERATED_SOURCE.startsWith("// Generated by")).toBe(true);
  });

  it("exposes the command and event namespaces", () => {
    expect(typeof commands.getSnapshot).toBe("function");
    expect(typeof events.snapshotUpdated.listen).toBe("function");
  });

  it("names its events the way the host emits them", () => {
    for (const name of [
      "snapshot-updated",
      "preferences-changed",
      "monitoring-state-changed",
      "overview-window-state-changed",
      "persistence-status-changed",
      "connection-progress-changed",
    ]) {
      expect(GENERATED_SOURCE).toContain(`"${name}"`);
    }
  });
});

describe("a command result", () => {
  it("records a typed domain failure as a domain failure", async () => {
    const delivered = await reportAsync(
      Promise.resolve({
        status: "error" as const,
        error: { kind: "account_not_found" as const },
      }),
    );

    expect(delivered).toBeNull();
    expect(getRendererState().failure?.kind).toBe("domain");
  });

  it("records a rejected call as a transport failure", async () => {
    const delivered = await reportAsync(commands.getSnapshot());

    expect(delivered).toBeNull();
    expect(getRendererState().failure?.kind).toBe("transport");
  });
});
