//! The one registry used for both mounting and exporting.
//!
//! Building the registry twice would let a command exist at runtime but be
//! missing from the generated TypeScript, or the reverse. This module exposes a
//! single constructor so that cannot happen.

use tauri_specta::Builder;

use crate::ipc::events::{
    ConnectionProgressChanged, MonitoringStateChanged, OverviewWindowStateChanged,
    PersistenceStatusChanged, PreferencesChanged, SnapshotUpdated, UpdatePromptChanged,
};

use crate::ipc::{
    commands, commands_connection, commands_prefs, commands_report, commands_update,
    commands_window,
};

/// Builds the registry with every command and event type collected.
#[must_use]
pub fn registry() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::get_snapshot,
            commands::list_provider_capabilities,
            commands::get_connection_progress,
            commands::set_monitoring_state,
            commands::set_account_enabled,
            commands::rename_account,
            commands::set_key_limit_shown,
            commands::disconnect_account,
            commands::refresh_accounts,
            commands_connection::begin_connection,
            commands_connection::cancel_connection,
            commands_connection::confirm_connection,
            commands_connection::reconnect_account,
            commands_prefs::update_preferences,
            commands_prefs::set_indicator_style,
            commands_prefs::set_polling_preferences,
            commands_prefs::clear_local_history,
            commands_prefs::export_sanitized_diagnostics,
            commands_window::set_overview_mode,
            commands_window::set_overview_always_on_top,
            commands_window::fit_overview_height,
            commands_window::set_app_view,
            commands_window::open_provider_usage_page,
            commands_window::open_settings_window,
            commands_report::open_bug_report_issue,
            commands_report::copy_bug_report_prompt,
            commands_update::get_update_prompt,
            commands_update::respond_to_update_prompt,
        ])
        .events(tauri_specta::collect_events![
            SnapshotUpdated,
            ConnectionProgressChanged,
            PreferencesChanged,
            MonitoringStateChanged,
            OverviewWindowStateChanged,
            PersistenceStatusChanged,
            UpdatePromptChanged,
        ])
}

/// Exports the TypeScript bindings to the renderer's generated directory.
///
/// # Errors
/// Returns [`BindingsError`] when the exporter cannot write the file.
pub fn export(builder: &Builder<tauri::Wry>) -> Result<(), BindingsError> {
    export_to(builder, DEFAULT_DESTINATION)
}

/// The path the renderer imports, relative to this crate's manifest directory.
pub const DEFAULT_DESTINATION: &str = "../src/generated/bindings.ts";

/// Exports the TypeScript bindings to `destination`.
///
/// # Errors
/// Returns [`BindingsError`] when the exporter cannot write the file.
pub fn export_to(
    builder: &Builder<tauri::Wry>,
    destination: impl AsRef<std::path::Path>,
) -> Result<(), BindingsError> {
    builder
        .export(
            specta_typescript::Typescript::default()
                // 64-bit revision counters are declared field by field in
                // `quota-contracts` with `#[specta(type = Number)]`, which is
                // how this pinned exporter version is told they travel as
                // JSON numbers rather than bigints.
                .header("// Generated by `cargo xtask bindings`. Do not edit by hand."),
            destination.as_ref(),
        )
        .map_err(|error| BindingsError {
            detail: error.to_string(),
        })
}

/// The exporter could not write the generated file.
#[derive(Debug, thiserror::Error)]
#[error("could not export the generated bindings: {detail}")]
pub struct BindingsError {
    /// The exporter's own message.
    pub detail: String,
}

impl From<BindingsError> for String {
    fn from(error: BindingsError) -> Self {
        error.detail
    }
}
