//! The one registry used for both mounting and exporting.
//!
//! Building the registry twice would let a command exist at runtime but be
//! missing from the generated TypeScript, or the reverse. This module exposes a
//! single constructor so that cannot happen.

use tauri_specta::{Builder, Event};

use crate::ipc::events::{
    ConnectionProgressChangedEvent, MonitoringStateChangedEvent, OverviewWindowStateChangedEvent,
    PersistenceStatusChangedEvent, PreferencesChangedEvent, SnapshotUpdatedEvent,
};

use crate::ipc::commands;

/// Builds the registry, mounts every handler and event, and exports bindings.
#[derive(Debug, thiserror::Error)]
pub enum BindingsError {
    /// The exporter could not write the generated file.
    #[error("could not export the generated bindings: {0}")]
    Export(String),
}

/// Builds the registry with every command and event type collected.
#[must_use]
pub fn registry() -> Builder {
    Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::get_snapshot,
            commands::list_provider_capabilities,
            commands::get_connection_progress,
            commands::begin_connection,
            commands::cancel_connection,
            commands::reconnect_account,
            commands::set_account_enabled,
            commands::rename_account,
            commands::disconnect_account,
            commands::refresh_accounts,
            commands::set_monitoring_state,
            commands::set_polling_preferences,
            commands::update_preferences,
            commands::set_overview_mode,
            commands::set_overview_always_on_top,
            commands::fit_overview_to_accounts,
            commands::reset_overview_position,
            commands::open_provider_usage_page,
            commands::clear_local_history,
            commands::export_sanitized_diagnostics,
        ])
        .events(tauri_specta::collect_events![
            SnapshotUpdatedEvent,
            ConnectionProgressChangedEvent,
            PreferencesChangedEvent,
            MonitoringStateChangedEvent,
            OverviewWindowStateChangedEvent,
            PersistenceStatusChangedEvent,
        ])
}

/// Exports the TypeScript bindings to the renderer's generated directory.
///
/// # Errors
/// Returns [`BindingsError::Export`] when the exporter cannot write the file.
pub fn export(
    builder: Builder<tauri::Wry>,
) -> Result<tauri_specta::Events<tauri::Wry>, BindingsError> {
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::String)
                .header(
                    "// @ts-nocheck\n// Generated by `cargo xtask bindings`. Do not edit by hand.",
                ),
            "../src/generated/bindings.ts",
        )
        .map_err(|error| BindingsError::Export(error.to_string()))
}
