//! The one registry used for both mounting and exporting.
//!
//! Building the registry twice would let a command exist at runtime but be
//! missing from the generated TypeScript, or the reverse. This module exposes a
//! single constructor so that cannot happen.

use tauri_specta::Builder;

use crate::ipc::events::{
    ConnectionProgressChanged, MonitoringStateChanged, OverviewWindowStateChanged,
    PersistenceStatusChanged, PreferencesChanged, SnapshotUpdated,
};

use crate::ipc::{commands, commands_connection, commands_prefs, commands_window};

/// Builds the registry with every command and event type collected.
#[must_use]
pub fn registry() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::get_snapshot,
            commands::list_provider_capabilities,
            commands::get_connection_progress,
            commands::set_monitoring_state,
            commands::set_account_enabled,
            commands::rename_account,
            commands::disconnect_account,
            commands::refresh_accounts,
            commands_connection::begin_connection,
            commands_connection::cancel_connection,
            commands_connection::reconnect_account,
            commands_prefs::update_preferences,
            commands_prefs::set_polling_preferences,
            commands_prefs::clear_local_history,
            commands_prefs::export_sanitized_diagnostics,
            commands_window::set_overview_mode,
            commands_window::set_overview_always_on_top,
            commands_window::fit_overview_to_accounts,
            commands_window::reset_overview_position,
            commands_window::activate_overview,
            commands_window::open_provider_usage_page,
        ])
        .events(tauri_specta::collect_events![
            SnapshotUpdated,
            ConnectionProgressChanged,
            PreferencesChanged,
            MonitoringStateChanged,
            OverviewWindowStateChanged,
            PersistenceStatusChanged,
        ])
}

/// Exports the TypeScript bindings to the renderer's generated directory.
///
/// # Errors
/// Returns [`BindingsError`] when the exporter cannot write the file.
pub fn export(builder: &Builder<tauri::Wry>) -> Result<(), BindingsError> {
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("// Generated by `cargo xtask bindings`. Do not edit by hand."),
            "../src/generated/bindings.ts",
        )
        .map_err(|error| BindingsError {
            detail: error.to_string(),
        })
}

/// The exporter could not write the generated file.
#[derive(Debug, thiserror::Error)]
#[error("could not export the generated bindings: {detail}")]
pub struct BindingsError {
    /// The exporter's own message.
    pub detail: String,
}

impl From<BindingsError> for String {
    fn from(error: BindingsError) -> Self {
        error.detail
    }
}
